SELECT TOP (1000) [CustomerID] 
      ,[NameStyle]
      ,[Title]
      ,[FirstName]
      ,[MiddleName]
      ,[LastName]
      ,[Suffix]
      ,[CompanyName]
  FROM [AdventureWorksLT2019].[SalesLT].[Customer]